detect if Dragon is installed and adapt

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -43,11 +43,10 @@ jobs:
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
-          if [[ "${{ matrix.python-version }}" == "3.9" ]]; then
-            pip install -e ".[dev,dask,radical_pilot]"
-          else
-            pip install -e ".[dev,dask,radical_pilot,dragon]"
-          fi
+          pip install -e ".[dev,dask,radical_pilot]"
+          # As of now Dragon only avilable in >= py3.10 and < 3.13. So 
+          # Install dragon if available for this Python version (fails gracefully if not)
+          pip install dragonhpc || echo "Dragon not available for Python ${{ matrix.python-version }}, skipping"
 
-      - name: Run pytest
-        run: pytest -n auto --dist loadscope --maxfail=3 --disable-warnings -q
+      - name: Run tests
+        run: make test-auto
